// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAloMHP0W_Ex-JQP80pEwJEoFBHzSzLrmI',
    appId: '1:1016275991800:web:b19bc465786271e30fcf0d',
    messagingSenderId: '1016275991800',
    projectId: 'figma-90d06',
    authDomain: 'figma-90d06.firebaseapp.com',
    storageBucket: 'figma-90d06.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUxaSB_-zIWxFRaWht6vl3opQHqW8oLqc',
    appId: '1:1016275991800:android:7c2e5727ea3bb6f20fcf0d',
    messagingSenderId: '1016275991800',
    projectId: 'figma-90d06',
    storageBucket: 'figma-90d06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeoo_QUEEAU8JA-QcEE-f_npVo34ktWfY',
    appId: '1:1016275991800:ios:45a14d416049bbc80fcf0d',
    messagingSenderId: '1016275991800',
    projectId: 'figma-90d06',
    storageBucket: 'figma-90d06.appspot.com',
    iosBundleId: 'com.example.figma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeoo_QUEEAU8JA-QcEE-f_npVo34ktWfY',
    appId: '1:1016275991800:ios:45a14d416049bbc80fcf0d',
    messagingSenderId: '1016275991800',
    projectId: 'figma-90d06',
    storageBucket: 'figma-90d06.appspot.com',
    iosBundleId: 'com.example.figma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAloMHP0W_Ex-JQP80pEwJEoFBHzSzLrmI',
    appId: '1:1016275991800:web:051f6413cd326d770fcf0d',
    messagingSenderId: '1016275991800',
    projectId: 'figma-90d06',
    authDomain: 'figma-90d06.firebaseapp.com',
    storageBucket: 'figma-90d06.appspot.com',
  );
}
